/*
 * Called when the contract changed and/or was (re-)deployed.
 * Updates the JS contract code in the frontend accordingly (ABI and address)
 * by wrapping the json data in the source file to JS and writing it to the destination file
 */

var fs = require('fs')
var process = require('process')

// 0 is the exec, 1 the js file being executed.
// Arg2 is the source file, Arg2 the destination file
const inFile = process.argv[2]
const outFile = process.argv[3]

const jsonStr = fs.readFileSync(inFile)

const outStr = `
// !!! this is autogenerated by a setup script. Changes will be overwritten !!!
const contract = ${jsonStr}`

fs.writeFileSync(outFile, outStr)
